### ISSUE TITLE
Crea facturas

### ISSUE THREAD

**Issue by antonalberdi** [catgento/magento-2-redsys#2]
Estoy utilizando esta extensión en mi magento 2.4 y a pesar de tener deshabilitada la opción de generar facturas automáticamente las sigue generando.

¿Hay alguna solución?

Gracias

**Comment by paugnu** [comment]
Hola @antonalberdi,

Efectivamente, he revisado el código y actualmente se ignora la variable de configuración para la generación de factura. 

Se puede arreglar fácilmente. Te contestaré aquí para que lo testees. ¿Estás utilizando composer o te has bajado un zip del módulo?

**Comment by antonalberdi** [comment]
Estoy utilizando composer, comentando la parte de generación de factura he conseguido que me funcione. Por lo demás el módulo está genial.  Muchas gracias!

**Comment by paugnu** [comment]
Gracias, @antonalberdi  :+1: 

He añadido al código el if necesario para que se tenga en cuenta ese campo. Con un composer update será suficiente para que actualices el módulo. ¿Podrás confirmarme que te funciona ben?

Un saludo,

**Comment by antonalberdi** [comment]
Funciona correctamente 👍

**Comment by paugnu** [comment]
Genial, cierro el issue :)
