### ISSUE TITLE
Error al utilizar un número de pedido personalizado

### ISSUE THREAD

**Issue by antonalberdi** [catgento/magento-2-redsys#4]
Tengo un error al utilizar un módulo externo que me permite personalizar los números (id) de pedido a mi gusto.

El error me aparece una vez redirigido a Redys y el mensaje es el siguiente: "error en datos enviados ".
 ¿Hay alguna solución aplicable en este modulo?

Gracias

**Comment by paugnu** [comment]
Hola @antonalberdi, ¿podrías indicarme de qué módulo se trata? Necesitaría poder reproducir el error para poder resolverlo.

**Comment by antonalberdi** [comment]
Se trata de este módulo:

https://meetanshi.com/magento-2-custom-order-number.html

**Comment by paugnu** [comment]
Gracias, lo reviso. Actualmente tengo un huevo de trabajo y no creo que pueda resolverlo rápidamente. Pero lo intentaré ;)

**Comment by paugnu** [comment]
Hola @antonalberdi,

He realizado algunos tests y el problema no está relacionado con el módulo de Redsys, sino con la numeración que pones al utilizar el módulo de meetanshi. Resulta que hay restricciones en la numeración de los pedidos que puedes utilizar en Redsys.

En esta tabla se definen las variables de entrada: https://pagosonline.redsys.es/parametros-entrada-salida.html#entradaTable

Ahí verás que el  DS_MERCHANT_ORDER (número de pedido), tiene restricciones. No puedes utilizar cualquier combinación. De hecho, indican:

> Se recomienda, por posibles problemas en el proceso de liquidación, que los 4 primeros dígitos sean numéricos. Para los dígitos restantes solo utilizar los siguientes caracteres ASCII:
> Del 48 = 0 al 57 = 9
> Del 65 = A al 90 = Z
> Del 97 = a al 122 = z

![image](https://user-images.githubusercontent.com/506393/102247616-74610f80-3f00-11eb-8dd3-8848679765f8.png)

Por lo tanto, no hay solución que yo pueda aportar. Debes cambiar la numeración de tus pedidos para que cumplan los requerimientos de Redsys.
